-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references REGISTRATIONPROCEDURE_ORGANIZATION(ID)^
create index IDX_SEC_USER_ON_ORGANIZATION on SEC_USER (ORGANIZATION_ID)^
-- end SEC_USER
