alter table SEC_ROLE drop column SYS_TENANT_ID__U55006 cascade ;
alter table SEC_ROLE drop column DEFAULT_SCREEN_ACCESS__U86561 cascade ;
alter table SEC_ROLE drop column DEFAULT_ENTITY_CREATE_ACCESS__U35400 cascade ;
alter table SEC_ROLE drop column DEFAULT_ENTITY_READ_ACCESS__U52623 cascade ;
alter table SEC_ROLE drop column DEFAULT_ENTITY_UPDATE_ACCESS__U59550 cascade ;
alter table SEC_ROLE drop column DEFAULT_ENTITY_DELETE_ACCESS__U48286 cascade ;
alter table SEC_ROLE drop column DEFAULT_ENTITY_ATTR_ACCESS__U72599 cascade ;
alter table SEC_ROLE drop column DEFAULT_SPECIFIC_ACCESS__U97327 cascade ;
alter table SEC_ROLE drop column SECURITY_SCOPE__U32262 cascade ;
