-- begin REGISTRATIONPROCEDURE_ORGANIZATION
create unique index IDX_REGISTRATIONPROCEDURE_ORGANIZATION_UK_INN on REGISTRATIONPROCEDURE_ORGANIZATION (INN) where DELETE_TS is null ^
-- end REGISTRATIONPROCEDURE_ORGANIZATION
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references REGISTRATIONPROCEDURE_ORGANIZATION(ID)^
create index IDX_SEC_USER_ON_ORGANIZATION on SEC_USER (ORGANIZATION_ID)^
-- end SEC_USER
